spring.application.name=multiple_databases

# Primary DB: MySQL
spring.datasource.mysql.jdbc-url=jdbc:mysql://localhost:3306/my_sql_db
spring.datasource.mysql.username=user
spring.datasource.mysql.password=root
spring.datasource.mysql.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.mysql.hikari.maximum-pool-size=5
spring.datasource.mysql.hikari.minimum-idle=1
# Secondary DB: Oracle
spring.datasource.mysql-secondary.jdbc-url=jdbc:mysql://localhost:3306/my_sql_db_secondary
spring.datasource.mysql-secondary.username=user
spring.datasource.mysql-secondary.password=root
spring.datasource.mysql-secondary.driver-class-name=com.mysql.cj.jdbc.Driver


# JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
